# Go Standard Library False Positives (Fixed in Go 1.25.5, incorrectly flagged)
- id: CVE-2025-61729
  statement: "Fixed in Go 1.25.5. False positive due to scanner DB lag."
- id: CVE-2025-58183
  statement: "Fixed in Go 1.25.2. False positive."
- id: CVE-2025-47907
  statement: "Fixed in Go 1.24.6. False positive."

# Ubuntu 24.04 Unpatched / Vendor Deferred Issues
- id: CVE-2016-2781
  statement: "Vulnerable in coreutils (Ubuntu 24.04). Old issue, often disputed/won't fix."
- id: CVE-2025-9086
  statement: "Vulnerable in curl (Ubuntu 24.04). No fix available."
- id: CVE-2024-52005
  statement: "Vulnerable in git (Ubuntu 24.04). Fix deferred by vendor."
- id: CVE-2022-3219
  statement: "Vulnerable in gnupg (Ubuntu 24.04). Fix deferred by upstream."
- id: CVE-2025-66382
  statement: "Vulnerable in expat (Ubuntu 24.04). Fix deferred by upstream."
- id: CVE-2024-2236
  statement: "Vulnerable in libgcrypt (Ubuntu 24.04). Fix deferred by upstream."
- id: CVE-2025-1180
  statement: "Vulnerable in binutils (Ubuntu 24.04). Status: Needs Evaluation / Low risk."
- id: CVE-2025-1149
  statement: "Memory leak in binutils (Ubuntu 24.04). Low severity/deferred."
- id: CVE-2025-1152
  statement: "Memory leak in binutils (Ubuntu 24.04). Low severity/deferred."
- id: CVE-2025-0167
  statement: "Low severity leakage in libcurl (rare .netrc usage). Suppress if unpatched."
- id: CVE-2025-10148
  statement: "Predictable WebSocket mask in curl (Ubuntu 24.04). No fix available. Low severity."
- id: CVE-2024-56433
  statement: "Shadow-utils subordinate ID config (Ubuntu 24.04). Unpatched/Low severity."
- id: CVE-2024-38950
  statement: "Libde265 Heap Buffer Overflow. Low impact media codec, not used in recon. Deferred in Ubuntu."
- id: CVE-2024-38949
  statement: "Libde265 Heap Buffer Overflow. Low impact media codec, not used in recon. Deferred in Ubuntu."
- id: CVE-2025-45582
  statement: "Tar path traversal. Unpatched in Ubuntu 24.04. Low severity in this context."
- id: CVE-2021-31879
  statement: "Wget auth header leak. Unpatched in Ubuntu 24.04."
- id: CVE-2024-41996
  statement: "OpenSSL DoS. Vulnerable in Ubuntu 24.04. Low severity (DoS only)."
- id: CVE-2015-2150
  statement: "Xen XSA-120. Hypervisor vulnerability. False positive for container."
- id: CVE-2021-45261
  statement: "Patch invalid pointer. Low severity/Unpatched in Ubuntu 24.04."
- id: CVE-2022-25836
  statement: "linux-libc-dev false positive (Host Kernel). Ignored package."
- id: CVE-2023-33053
  statement: "linux-libc-dev false positive (Host Kernel). Ignored package."
- id: CVE-2019-20426
  statement: "linux-libc-dev false positive (Host Kernel). Ignored package."
- id: CVE-2017-13165
  statement: "linux-libc-dev false positive (Host Kernel). Ignored package."
- id: CVE-2017-0537
  statement: "linux-libc-dev false positive (Host Kernel). Ignored package."
- id: CVE-2019-14899
  statement: "Host Kernel Vulnerability (VPN). False positive for container."
- id: CVE-2021-26934
  statement: "Host Kernel Vulnerability (Xen). False positive for container."
- id: CVE-2024-36331
  statement: "Host Kernel Vulnerability (CPU Cache). False positive for container."
- id: CVE-2021-33098
  statement: "Host Driver Vulnerability (FPGA). False positive for container."
