# Go Standard Library False Positives (Fixed in Go 1.25.5, incorrectly flagged)
- id: CVE-2025-61729
  statement: "Fixed in Go 1.25.5. False positive due to scanner DB lag."
- id: CVE-2025-58183
  statement: "Fixed in Go 1.25.2. False positive."
- id: CVE-2025-47907
  statement: "Fixed in Go 1.24.6. False positive."

# Ubuntu 24.04 Unpatched / Vendor Deferred Issues
- id: CVE-2016-2781
  statement: "Vulnerable in coreutils (Ubuntu 24.04). Old issue, often disputed/won't fix."
- id: CVE-2025-9086
  statement: "Vulnerable in curl (Ubuntu 24.04). No fix available."
- id: CVE-2024-52005
  statement: "Vulnerable in git (Ubuntu 24.04). Fix deferred by vendor."
- id: CVE-2022-3219
  statement: "Vulnerable in gnupg (Ubuntu 24.04). Fix deferred by upstream."
- id: CVE-2025-66382
  statement: "Vulnerable in expat (Ubuntu 24.04). Fix deferred by upstream."
- id: CVE-2024-2236
  statement: "Vulnerable in libgcrypt (Ubuntu 24.04). Fix deferred by upstream."
- id: CVE-2025-1180
  statement: "Vulnerable in binutils (Ubuntu 24.04). Status: Needs Evaluation / Low risk."
- id: CVE-2025-1149
  statement: "Memory leak in binutils (Ubuntu 24.04). Low severity/deferred."
- id: CVE-2025-1152
  statement: "Memory leak in binutils (Ubuntu 24.04). Low severity/deferred."
